In [3]:
from scipy.linalg import solve_banded
import numpy as np

In [4]:
ab = np.array([[0,  0, -1, -1, -1],
               [0,  2,  2,  2,  2],
               [5,  4,  3,  2,  1],
               [1,  1,  1,  1,  0]])

In [7]:
ab

array([[ 0,  0, -1, -1, -1],
       [ 0,  2,  2,  2,  2],
       [ 5,  4,  3,  2,  1],
       [ 1,  1,  1,  1,  0]])

In [6]:
b = np.array([0, 1, 2, 2, 3])

In [10]:
b

array([0, 1, 2, 2, 3])

In [8]:
x = solve_banded((1, 2), ab, b)

In [9]:
x

array([-2.37288136,  3.93220339, -4.        ,  4.3559322 , -1.3559322 ])